-- ~/.config/nvim/init.lua
-- Shared between terminal Neovim and VS Code (vscode-neovim extension)

-- Leader key (set BEFORE any mappings)
vim.g.mapleader = " "
vim.g.maplocalleader = ","

-- Map Backspace as a second Leader key (split keyboard: both thumbs get leader)
-- Modes: normal, visual/visual-block, operator-pending. NOT insert (BS must delete).
vim.keymap.set({ "n", "v", "o" }, "<BS>", "<Space>", { remap = true })

------------------------------------------------------------------------
-- Shared settings (apply everywhere)
------------------------------------------------------------------------
local opt = vim.opt

opt.ignorecase = true       -- case-insensitive search...
opt.smartcase = true        -- ...unless you type a capital
opt.incsearch = true        -- show matches as you type
opt.hlsearch = true         -- highlight search results

opt.clipboard = "unnamedplus" -- use system clipboard

opt.scrolloff = 8           -- keep 8 lines visible above/below cursor
opt.sidescrolloff = 8

opt.timeoutlen = 400        -- ms to wait for mapped sequence

------------------------------------------------------------------------
-- Shared keymaps
------------------------------------------------------------------------
local map = vim.keymap.set

-- Clear search highlight
map("n", "<Leader>/", "<Cmd>nohlsearch<CR>", { desc = "Clear search highlight" })

-- Stay in visual mode after indenting
map("v", "<", "<gv", { desc = "Indent left and reselect" })
map("v", ">", ">gv", { desc = "Indent right and reselect" })

-- Move lines up/down in visual mode
map("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move selection down" })
map("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move selection up" })

-- Don't overwrite register when pasting over selection
map("x", "p", '"_dP', { desc = "Paste without yanking replaced text" })

------------------------------------------------------------------------
-- Terminal-only settings (skip in VS Code)
------------------------------------------------------------------------
if not vim.g.vscode then
  opt.number = true           -- line numbers
  opt.relativenumber = true   -- relative line numbers
  opt.signcolumn = "yes"      -- always show sign column
  opt.cursorline = true       -- highlight current line
  opt.termguicolors = true    -- 24-bit color
  opt.wrap = false            -- no line wrapping
  opt.splitbelow = true       -- horizontal splits go below
  opt.splitright = true       -- vertical splits go right
  opt.undofile = true         -- persistent undo

  opt.tabstop = 2
  opt.shiftwidth = 2
  opt.expandtab = true        -- spaces, not tabs
  opt.smartindent = true

  -- Python: 4-space indent per PEP 8
  vim.api.nvim_create_autocmd("FileType", {
    pattern = "python",
    callback = function()
      vim.opt_local.tabstop = 4
      vim.opt_local.shiftwidth = 4
    end,
  })

  -- Better window navigation
  map("n", "<C-h>", "<C-w>h", { desc = "Move to left window" })
  map("n", "<C-j>", "<C-w>j", { desc = "Move to below window" })
  map("n", "<C-k>", "<C-w>k", { desc = "Move to above window" })
  map("n", "<C-l>", "<C-w>l", { desc = "Move to right window" })
end

------------------------------------------------------------------------
-- VS Code-only settings
------------------------------------------------------------------------
if vim.g.vscode then
  local vscode = require("vscode")

  -- IDEAS GENERATED BY COPILOT FOR REFERENCE
  -- -- ── Files / Find ───────────────────────────────────────────────
  -- map("n", "<Leader>ff", function() vscode.action("workbench.action.quickOpen") end, { desc = "Find file" })
  -- map("n", "<Leader>fg", function() vscode.action("workbench.action.findInFiles") end, { desc = "Find in files (grep)" })
  -- map("n", "<Leader>fr", function() vscode.action("workbench.action.openRecent") end, { desc = "Recent files/folders" })
  -- map("n", "<Leader>fn", function() vscode.action("workbench.action.files.newUntitledFile") end, { desc = "New file" })
  -- map("n", "<Leader>fs", function() vscode.action("workbench.action.files.save") end, { desc = "Save file" })
  -- map("n", "<Leader>fS", function() vscode.action("workbench.action.files.saveAll") end, { desc = "Save all files" })
  -- map("n", "<Leader>fp", function() vscode.action("workbench.action.showCommands") end, { desc = "Command palette" })
  -- map("n", "<Leader>fw", function() vscode.action("workbench.action.findInFiles", { args = { query = vim.fn.expand("<cword>") } }) end, { desc = "Find word under cursor" })

  -- -- ── Explorer / Sidebar ─────────────────────────────────────────
  -- map("n", "<Leader>e",  function() vscode.action("workbench.view.explorer") end, { desc = "Explorer" })
  -- map("n", "<Leader>E",  function() vscode.action("workbench.files.action.showActiveFileInExplorer") end, { desc = "Reveal file in explorer" })

  -- ── Code Navigation (supplements vscode-neovim built-ins) ──────
  -- Built-in: gd (definition), gD (peek def), gh/K (hover),
  --           gf (declaration), gO (file symbols), gH (references)
  --           TODO: add ones for adding/removing lines without ending up in insert mode or even moving cursor
  --           TODO: shift tab should un-indent
  map("n", "<Leader>d",     function() vscode.action("editor.action.revealDefinition") end, { desc = "Go to definition" })
  map("n", "<Leader>D",     function() vscode.action("editor.action.revealDeclaration") end, { desc = "Go to declaration" })
  map("n", "<Leader>h",     function() vscode.action("editor.action.showHover") end, { desc = "Hover" })
  map("n", "<Leader>p",     function() vscode.action("editor.action.triggerParameterHints") end, { desc = "Trigger Parameter Hints" })
  map("n", "<Leader>f",     function() vscode.action("editor.action.quickFix") end, { desc = "Code action / quick fix" })
  -- map("n", "gr",         function() vscode.action("editor.action.goToReferences") end, { desc = "Go to references" })
  -- map("n", "gi",         function() vscode.action("editor.action.goToImplementation") end, { desc = "Go to implementation" })
  -- map("n", "gy",         function() vscode.action("editor.action.goToTypeDefinition") end, { desc = "Go to type definition" })
  -- map("n", "gI",         function() vscode.action("editor.action.peekImplementation") end, { desc = "Peek implementation" })
  -- map("n", "gY",         function() vscode.action("editor.action.peekTypeDefinition") end, { desc = "Peek type definition" })

  -- -- ── Symbols ────────────────────────────────────────────────────
  -- map("n", "<Leader>ss", function() vscode.action("workbench.action.gotoSymbol") end, { desc = "Go to symbol in file" })
  -- map("n", "<Leader>sS", function() vscode.action("workbench.action.showAllSymbols") end, { desc = "Go to symbol in workspace" })
  -- map("n", "<Leader>so", function() vscode.action("outline.focus") end, { desc = "Focus outline view" })

  -- -- ── Code Actions / Refactoring ─────────────────────────────────
  -- map("n", "<Leader>ca", function() vscode.action("editor.action.quickFix") end, { desc = "Code action / quick fix" })
  -- map("v", "<Leader>ca", function() vscode.action("editor.action.quickFix") end, { desc = "Code action / quick fix" })
  -- map("n", "<Leader>cr", function() vscode.action("editor.action.rename") end, { desc = "Rename symbol" })
  -- map("n", "<Leader>cf", function() vscode.action("editor.action.formatDocument") end, { desc = "Format document" })
  -- map("v", "<Leader>cf", function() vscode.action("editor.action.formatSelection") end, { desc = "Format selection" })
  -- map("n", "<Leader>co", function() vscode.action("editor.action.organizeImports") end, { desc = "Organize imports" })
  -- map("n", "<Leader>cR", function() vscode.with_insert(function() vscode.action("editor.action.refactor") end) end, { desc = "Refactor" })
  -- map("v", "<Leader>cR", function() vscode.with_insert(function() vscode.action("editor.action.refactor") end) end, { desc = "Refactor" })
  -- map("n", "<Leader>cs", function() vscode.action("editor.action.sourceAction") end, { desc = "Source action" })

  -- -- ── Comments ───────────────────────────────────────────────────
  -- map("n", "<Leader>cc", function() vscode.action("editor.action.commentLine") end, { desc = "Toggle line comment" })
  -- map("v", "<Leader>cc", function() vscode.action("editor.action.commentLine") end, { desc = "Toggle line comment" })
  -- map("n", "<Leader>cB", function() vscode.action("editor.action.blockComment") end, { desc = "Toggle block comment" })
  -- map("v", "<Leader>cB", function() vscode.action("editor.action.blockComment") end, { desc = "Toggle block comment" })

  -- -- ── Diagnostics / Problems ─────────────────────────────────────
  -- map("n", "<Leader>xx", function() vscode.action("workbench.actions.view.problems") end, { desc = "Problems panel" })
  -- map("n", "]d",         function() vscode.action("editor.action.marker.nextInFiles") end, { desc = "Next diagnostic" })
  -- map("n", "[d",         function() vscode.action("editor.action.marker.prevInFiles") end, { desc = "Prev diagnostic" })
  -- map("n", "]e",         function() vscode.action("editor.action.marker.next") end, { desc = "Next error (this file)" })
  -- map("n", "[e",         function() vscode.action("editor.action.marker.prev") end, { desc = "Prev error (this file)" })

  -- -- ── Buffers / Editors ──────────────────────────────────────────
  -- map("n", "<Leader>bb", function() vscode.action("workbench.action.showAllEditors") end, { desc = "Show all editors" })
  -- map("n", "<Leader>bd", function() vscode.action("workbench.action.closeActiveEditor") end, { desc = "Close editor" })
  -- map("n", "<Leader>bo", function() vscode.action("workbench.action.closeOtherEditors") end, { desc = "Close other editors" })
  -- map("n", "<Leader>bD", function() vscode.action("workbench.action.closeAllEditors") end, { desc = "Close all editors" })
  -- map("n", "<Leader>bp", function() vscode.action("workbench.action.pinEditor") end, { desc = "Pin/unpin editor" })
  -- map("n", "]b",         function() vscode.action("workbench.action.nextEditor") end, { desc = "Next editor" })
  -- map("n", "[b",         function() vscode.action("workbench.action.previousEditor") end, { desc = "Prev editor" })

  -- -- ── Window / Splits ────────────────────────────────────────────
  -- map("n", "<Leader>wv", function() vscode.action("workbench.action.splitEditorRight") end, { desc = "Split right" })
  -- map("n", "<Leader>ws", function() vscode.action("workbench.action.splitEditorDown") end, { desc = "Split down" })
  -- map("n", "<Leader>wq", function() vscode.action("workbench.action.closeEditorsInGroup") end, { desc = "Close editor group" })
  -- map("n", "<Leader>wo", function() vscode.action("workbench.action.joinAllGroups") end, { desc = "Close other groups" })
  -- map("n", "<Leader>w=", function() vscode.action("workbench.action.evenEditorWidths") end, { desc = "Equal editor widths" })

  -- -- ── Git ────────────────────────────────────────────────────────
  -- map("n", "<Leader>gg", function() vscode.action("workbench.view.scm") end, { desc = "Source control panel" })
  -- map("n", "<Leader>gb", function() vscode.action("gitlens.toggleLineBlame") end, { desc = "Toggle line blame (GitLens)" })
  -- map("n", "<Leader>gB", function() vscode.action("git.checkout") end, { desc = "Checkout branch" })
  -- map("n", "<Leader>gc", function() vscode.action("git.commit") end, { desc = "Git commit" })
  -- map("n", "<Leader>gp", function() vscode.action("git.push") end, { desc = "Git push" })
  -- map("n", "<Leader>gl", function() vscode.action("git.pull") end, { desc = "Git pull" })
  -- map("n", "<Leader>gd", function() vscode.action("git.openChange") end, { desc = "Open changes (diff)" })
  -- map("n", "<Leader>gs", function() vscode.action("git.stageSelectedRanges") end, { desc = "Stage selection" })
  -- map("n", "<Leader>gu", function() vscode.action("git.unstageSelectedRanges") end, { desc = "Unstage selection" })
  -- map("n", "]h",         function() vscode.action("workbench.action.editor.nextChange") end, { desc = "Next git change" })
  -- map("n", "[h",         function() vscode.action("workbench.action.editor.previousChange") end, { desc = "Prev git change" })

  -- -- ── Debug ──────────────────────────────────────────────────────
  -- map("n", "<Leader>db", function() vscode.action("editor.debug.action.toggleBreakpoint") end, { desc = "Toggle breakpoint" })
  -- map("n", "<Leader>dB", function() vscode.action("editor.debug.action.conditionalBreakpoint") end, { desc = "Conditional breakpoint" })
  -- map("n", "<Leader>dc", function() vscode.action("workbench.action.debug.continue") end, { desc = "Continue / start" })
  -- map("n", "<Leader>di", function() vscode.action("workbench.action.debug.stepInto") end, { desc = "Step into" })
  -- map("n", "<Leader>do", function() vscode.action("workbench.action.debug.stepOut") end, { desc = "Step out" })
  -- map("n", "<Leader>dO", function() vscode.action("workbench.action.debug.stepOver") end, { desc = "Step over" })
  -- map("n", "<Leader>dp", function() vscode.action("workbench.action.debug.pause") end, { desc = "Pause" })
  -- map("n", "<Leader>dq", function() vscode.action("workbench.action.debug.stop") end, { desc = "Stop" })
  -- map("n", "<Leader>dr", function() vscode.action("workbench.action.debug.restart") end, { desc = "Restart" })
  -- map("n", "<Leader>dd", function() vscode.action("workbench.view.debug") end, { desc = "Debug panel" })

  -- -- ── Terminal ───────────────────────────────────────────────────
  -- map("n", "<Leader>tt", function() vscode.action("workbench.action.terminal.toggleTerminal") end, { desc = "Toggle terminal" })
  -- map("n", "<Leader>tn", function() vscode.action("workbench.action.terminal.new") end, { desc = "New terminal" })
  -- map("n", "<Leader>ts", function() vscode.action("workbench.action.terminal.split") end, { desc = "Split terminal" })

  -- ── Navigation ─────────────────────────────────────────────────
  -- vscode-neovim uses VSCode's jumplist; bind explicitly for reliability
  map("n", "<C-o>",      function() vscode.action("workbench.action.navigateBack") end, { desc = "Navigate back" })
  map("n", "<C-i>",      function() vscode.action("workbench.action.navigateForward") end, { desc = "Navigate forward" })

  -- -- ── Multi-cursor ───────────────────────────────────────────────
  -- map({ "n", "x", "i" }, "<C-d>", function()
  --   vscode.with_insert(function()
  --     vscode.action("editor.action.addSelectionToNextFindMatch")
  --   end)
  -- end, { desc = "Add selection to next match" })

  -- -- ── UI Toggles ─────────────────────────────────────────────────
  -- map("n", "<Leader>uz", function() vscode.action("workbench.action.toggleZenMode") end, { desc = "Zen mode" })
  -- map("n", "<Leader>uw", function() vscode.action("editor.action.toggleWordWrap") end, { desc = "Toggle word wrap" })
  -- map("n", "<Leader>um", function() vscode.action("editor.action.toggleMinimap") end, { desc = "Toggle minimap" })
  -- map("n", "<Leader>ub", function() vscode.action("workbench.action.toggleSidebarVisibility") end, { desc = "Toggle sidebar" })
  -- map("n", "<Leader>up", function() vscode.action("workbench.action.togglePanel") end, { desc = "Toggle panel" })
  -- map("n", "<Leader>uf", function() vscode.action("workbench.action.toggleFullScreen") end, { desc = "Toggle full screen" })
end
